feat: Add pwd command
mohanad-80/Command_Line_Interpreter pull request #2
Opened 2024-10-26 21:25 UTC by AhmedEhab2022

Make pwd command:
- return current working directory
- it works with any argument passed like (pwd cat => <current_working_directory>)

2024-10-26 22:08 UTC, mohanad-80 requested changes

2024-10-26 22:08 UTC, mohanad-80 commented on src/interpreter/commands/PwdCommand.java
> +        context.setCurrentDirectory(System.getProperty("user.dir"));
Why are you setting the current directory?
The command should return the current directory not update it.
You should only get it and then return it as a string.

2024-10-26 22:08 UTC, mohanad-80 commented on src/interpreter/CommandHandler.java
> +          writer.write(output + '\n');
Did you test the command with the >> or > operators?

2024-10-27 05:40 UTC, AhmedEhab2022 commented on src/interpreter/CommandHandler.java
> +          writer.write(output + '\n');
Yes, i test it with > and >> in git bash and by default add new line after the content

2024-10-27 05:44 UTC, AhmedEhab2022 commented on src/interpreter/commands/PwdCommand.java
> +        context.setCurrentDirectory(System.getProperty("user.dir"));
When i use it it get my home directory as you made in the constructor so i use set property and i searched about it and get this
 https://stackoverflow.com/questions/4871051/how-to-get-the-current-working-directory-in-java

2024-10-27 22:25 UTC, closed without merging